### ISSUE TITLE
Scheduler\Base fails to inject contentObject into UriBuilder, crash when creating typolink via cli_dispatch

### ISSUE THREAD

**Issue by pdanzinger** [aimeos/aimeos-typo3#51] opened 2017-03-29 10:16 UTC
Currently, trying to create a typolink in a "cli_dispatch.phpsh"-environment causes a null pointer exception on $uriBuilder->contentObject. 

\Aimeos\Aimeos\Scheduler\Base::getUriBuilder() creates a UriBuilder and injects a ConfigurationManager containing a content object. However, the content object is only ever copied into the UriBuilder itself on UriBuilder::initializeObject(), which is only called on object creation (i.e. before aimeos injects the configuration manager).

Calling the scheduler via the TYPO3 backend works fine, presumably because the backend environment automatically creates a content object.

Adding a call to $uriBuilder->initializeObject() in Scheduler\Base::getUriBuilder() worked for me, but I'm not sure about regressions.

Tested with TYPO3 7.6.16 and aimeos-typo3 2017.03.x-dev
Stack trace for reference:
```
#0  Aimeos\Aimeos\Base\View::get() called at [{ TYPO3 root }\web\typo3conf\ext\aimeos\Classes\Base.php:204]
#1  Aimeos\Aimeos\Base::getView() called at [{ TYPO3 root }\web\typo3conf\ext\aimeos\Classes\Scheduler\Base.php:83]
#2  Aimeos\Aimeos\Scheduler\Base::getContext() called at [{ TYPO3 root }\web\typo3conf\ext\aimeos\Classes\Scheduler\Base.php:34]
#3  Aimeos\Aimeos\Scheduler\Base::execute() called at [{ TYPO3 root }\web\typo3conf\ext\aimeos\Classes\Scheduler\Task\Typo6.php:42]
#4  Aimeos\Aimeos\Scheduler\Task\Typo6->execute() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\sysext\scheduler\Classes\Scheduler.php:158]
#5  TYPO3\CMS\Scheduler\Scheduler->executeTask() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\sysext\scheduler\Classes\Controller\SchedulerCliController.php:145]
#6  TYPO3\CMS\Scheduler\Controller\SchedulerCliController->loopTasks() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\sysext\scheduler\Classes\Controller\SchedulerCliController.php:99]
#7  TYPO3\CMS\Scheduler\Controller\SchedulerCliController->run() called at [{ TYPO3 root }\web\typo3temp\Cache\Code\cache_core\ext_localconf_2f843201ce16b0560cff44f7ecbba89aeedc2e96.php:1056]
#8  TYPO3\CMS\Core\Cache\Backend\SimpleFileBackend->{closure}()
#9  call_user_func() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\sysext\backend\Classes\Console\CliRequestHandler.php:69]
#10 TYPO3\CMS\Backend\Console\CliRequestHandler->handleRequest() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\sysext\core\Classes\Core\Bootstrap.php:302]
#11 TYPO3\CMS\Core\Core\Bootstrap->handleRequest() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\sysext\backend\Classes\Console\Application.php:73]
#12 TYPO3\CMS\Backend\Console\Application->run() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\cli_dispatch.phpsh:26]
#13 {closure}()
#14 call_user_func() called at [{ TYPO3 root }\vendor\typo3\cms\typo3\cli_dispatch.phpsh:27]
```

**Comment by aimeos** [comment] 2017-03-29 10:49
Don't think there will be any regressions by adding `$uriBuilder->initializeObject()`.
Can you create a pull request?

**Comment by gilbertsoft** [comment] 2017-03-29 11:08
I'm wondering a little bit about your issue, because this method should be called after content object creation. Can you share your code for an exacter investigation? Perhaps there is an error in the core too...

**Comment by pdanzinger** [comment] 2017-03-29 15:57
TYPO3 itself does call the function when instantiating the object, that's not the problem.

Basically, the \TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder class is configured via an object of type \TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface. Usually this is automatically injected with extbase. And on its live-cycle initialize method, it copies the content object form the ConfigurationManager into itself:
```
class UriBuilder {
[...]
     /**
     * @param \TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface $configurationManager
     */
    public function injectConfigurationManager(\TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface $configurationManager)
    {
        $this->configurationManager = $configurationManager;
    }
[...]
    /**
     * Life-cycle method that is called by the DI container as soon as this object is completely built
     *
     * @return void
     */
    public function initializeObject()
    {
        $this->contentObject = $this->configurationManager->getContentObject();
    }
[...]
}
```

However, cli_dispatch doesn't automatically provide a content object. Aimeos creates its own ConfigurationManager and content object, and manually calls the extbase inject method. Simplified code example:
```
$contentObjectRenderer = $objectManager->get( 'TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer' );
$configurationManager = $objectManager->get( 'TYPO3\CMS\Extbase\Configuration\ConfigurationManager' );
$configurationManager->setContentObject( $contentObjectRenderer );

$uriBuilder = $objectManager->get( 'TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder' );
$uriBuilder->injectConfigurationManager( $configurationManager );

return uriBuilder;
```

The current issue is that although the configuration manager is replaced, the initialize method isn't called a second time and thus the content object reference inside the UriBuilder is still empty.

**Comment by gilbertsoft** [comment] 2017-03-29 16:03
OK, then it's fine because the initialize method should be called only once!

**Comment by aimeos** [comment] 2017-03-31 08:15
PR is merged

**Closed by aimeos** 2017-03-31 08:15 UTC
