### ISSUE TITLE
Edit Product breaks with &quot;

### ISSUE THREAD

**Issue by infabo** [aimeos/aimeos-typo3#109] opened 2019-10-08 16:55 UTC
When you have a product text containing `&quot;` it breaks the backend product edit view. It causes a memory leak and the browser would crash within seconds.

![image](https://user-images.githubusercontent.com/3999104/66416134-788cc580-e9fd-11e9-817b-357553cfc2ca.png)

after some investigation the cause for this:

when a product text (`mshop_text` record) contains a `&quot;` in the `content`-column it produces a big fat memory leak.

steps to reproduce:
edit or add a product. add/edit a product-text and switch off the RTE. add for example `&quot;Gold&quot;` and save. Now it is broken.

It was working in the old JS-admin backend, but is broken since backend-admin was migrated to vue.js

**Comment by aimeos** [comment] 2019-10-08 17:07
What was the last working version and which one do you use now?

**Comment by infabo** [comment] 2019-10-09 06:34
As far as I am aware of, editing affected products was only passible in the old "ExtJS admin expert mode". But this was removed in 18.x. So I assume it was working until 17.x.

**Comment by infabo** [comment] 2019-10-09 06:35
Now using 18.10.9. But same behaviour with 19.7.3.

**Comment by aimeos** [comment] 2019-10-09 09:16
We've tested with your example `&quot;Gold&quot;` in dev-master and 2018.10 at http://admin.demo.aimeos.org with Chrome and Firefox (both latest stable) but had no problems with a memory leak. Which browser are you using? Do you use a modified configuration for CKEditor?

**Comment by infabo** [comment] 2019-10-10 10:53
Hey,

I am at http://admin.demo.aimeos.org/ and I am able to break it.

I don't know why you aren't able to reproduce. Just disable the RTE and enter the provided sample `&quot;`

![image](https://user-images.githubusercontent.com/3999104/66562820-b9e7b700-eb5c-11e9-82ce-56739a9a8afb.png)

It needs to look like this:

![image](https://user-images.githubusercontent.com/3999104/66562923-f3b8bd80-eb5c-11e9-9efb-403cc86028d0.png)

**Comment by infabo** [comment] 2019-10-10 10:58
So, NO. we are not using any customized CKeditor config (at least not that customized).

Let me clearify:

With CKEditor enabled you won't be able to break it. CKEditor does not convert `"Gold"` to `&quot;Gold&quot;`. This means: no, CKEditor does not convert `"` to `&quot;`.

### So why this happended then?

I don't know. One of the affected texts was last modified in 2017! In the meantime there were several updates of Aimeos and TYPO3 8. Very long time ago all texts were maintained via the old ExtJS Super-Admin-Expert-Mode interface. This interface that looked like an ugly excel sheet. I can't remember exactly - but it was ugly as hell. So I don't know which RTE there was - was there even an RTE in that interface? We won't find out - no time-machine for 2017 here.

**Comment by infabo** [comment] 2019-10-10 11:02
Browsers I can confirm:

* Chromium 76.0.3809.132
* Firefox 69.0.1 (at least Firefox does not die completely - just super slows-down)

**Comment by aimeos** [comment] 2019-10-10 11:37
Can confirm that by reproducing your steps. It's only going to break if `&quot;` is stored in the database. The CKEditor in the Aimeos admin interface is configured to don't convert `"` to `&quot;` so it wasn't a problem up to now.

This seems to be a CKEditor problem and we've added a bug report:
https://github.com/ckeditor/ckeditor4/issues/3565

**Comment by infabo** [comment] 2019-10-11 06:10
I guess the most likely scenario is, that `&quot` has been stored any time in the past. These products now can't be edited anymore. Another possible scenario, when someone updates product-texts low-level via an import/sync script.

**Comment by infabo** [comment] 2019-10-11 06:18
Did not track down, because the performance tool got stuck. But at least I could find out, it is some `setAttribute` call which has very much CPU time. I guess this does not has its origin in CKEditor.

**Comment by aimeos** [comment] 2019-10-11 10:07
Problem wasn't CKEditor but an invalid encoding of `&quot;` in JSON data e.g.
`{"key": "&quot;"}` became `{&quot;key&quot;: &quot;&quot;&quot;}` in HTML attribute which can't parsed correctly and the jQuery or Vue.js parser tried to return a useful result nevertheless. This resulted in a high CPU load.

The fix is to use `json_encode( $data, JSON_HEX_AMP )` that will encode to `{"key": "\u0026quot;"}` and in HTML attributes it becomes `{&quot;key&quot;: &quot;\u0026quot;&quot;}` which can be parsed without problems.

The fix (https://github.com/aimeos/ai-admin-jqadm/commit/10cb8913a2eb14402fec2dff0c2ef071b9ba7e9b) will be part of the upcoming 19.10 release next week. Thank you for reporting! :-)

**Closed** 2019-10-11 10:08 UTC

**Comment by infabo** [comment] 2019-10-11 13:46
Thanks!
