### ISSUE TITLE
Scheduler not working (Undefined array key)

### ISSUE THREAD

**Issue by noaluzzi** [aimeos/aimeos-typo3#187] opened 2022-08-25 13:27 UTC
Typo3 v11.5.15, Aimeos 22.7.1
If I want to add a new Scheduler Task, the following errors appear:
`PHP Warning: Undefined array key "aimeos_controller" in /var/www/html/public/typo3conf/ext/aimeos/Classes/Scheduler/Provider/AbstractProvider.php line 55
PHP Warning: Undefined array key "aimeos_sender_from" in /var/www/html/public/typo3conf/ext/aimeos/Classes/Scheduler/Provider/Email.php line 61`

Seems to be an error somehow connected to the getFields() function in all of the files in the /ext/aimeos/Classes/Scheduler/ directory.

**Comment by aimeos** [comment] 2022-08-26 09:04
Seems like you haven't filled in the sender e-mail address

**Comment by noaluzzi** [comment] 2022-08-26 12:34
Thank you for the fast answer. Sorry I didn't explain it enough: The field for the sender address isn't being generated for it ot be filled. None of the aimeos related fields are being rendered in the backend for them to fill. That's why I suppose something not working aîn the getFields() function.

**Comment by aimeos** [comment] 2022-08-26 13:23
Yes, that's the root cause. Can you check if there are any errors in the log that may cause the problem?

**Comment by noaluzzi** [comment] 2022-08-29 06:22
The Log is giving me the following error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Aimeos\Aimeos\Scheduler\Provider\Email6::getFields() | Error thrown in file /var/www/html/public/typo3conf/ext/aimeos/Classes/Scheduler/Provider/Email6.php in line 40. Requested URL: http://www.localhost/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&SET%5Bfunction%5D=scheduler&CMD=add&tx_scheduler%5Bclass%5D=Aimeos%5CAimeos%5CScheduler%5CTask%5CEmail6 `

**Comment by aimeos** [comment] 2022-08-29 06:42
The method is inherited from the Email class:
https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Scheduler/Provider/Email6.php#L19
https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Scheduler/Provider/Email.php#L51

Which PHP Version are you using? PHP 8.0 till 8.0.10 where buggy and caused such problems.

**Comment by noaluzzi** [comment] 2022-08-29 06:44
The application is running on PHP 8.1.9.

**Comment by aimeos** [comment] 2022-08-29 06:47
We are running the same version without problems but it's a bug in the PHP interpreter nevertheless.
For testing, you can try to switch off the PHP OPCache and see if it works afterwards.

**Comment by noaluzzi** [comment] 2022-08-29 13:15
I switched off PHP OPCache and the errors remain. Tried re-installing the whole application twice without any success.

**Comment by aimeos** [comment] 2022-08-29 14:40
Because it's an error in the PHP interpreter, re-installing the application won't help.

**Comment by noaluzzi** [comment] 2022-08-29 15:07
So the same error occurs on:
- Local installation on Docker, PHP 8.1.9
- Server installation, PHP 8.1.9

**Comment by noaluzzi** [comment] 2022-08-30 09:08
I got rid of all errors and the scheduler works perfectly fine by replacing all (for each field):
`$taskInfo[$this->fieldController] = (array) $taskInfo[$this->fieldController];`
with (for each field):
`(isset($taskInfo[$this->fieldController]) ? (array) $taskInfo[$this->fieldController] : $taskInfo[$this->fieldController] = []);`
 in the files aimeos/Classes/Scheduler/Provider/AbstractProvider.php and aimeos/Classes/Scheduler/Provider/Email.php

**Comment by aimeos** [comment] 2022-08-31 07:27
Unfortunately, these fields are not optional and you need them for selecting which site and job controller should be used (as well as additional configuration). The underlying problem in your setup is that the fields are not rendered and this must be fixed instead.

**Comment by aimeos** [comment] 2022-09-08 12:00
We've made several tests now with the same PHP version (8.1.9), same TYPO3 version (11.5.15) and same Aimeos version (22.7.1) but we were unable to reproduce the problem. It might be a strange PHP bug which only occurs rarely but such things are hard to track and even harder to fix. We also can't make the fields optional because they are required. Sorry, but we don't have a solution yet for your problem :-(

**Comment by aimeos** [comment] 2022-09-08 12:04
We leave the issue open, if others face the same problem. Then, maybe we can get closer to get a solution.

**Comment by aimeos** [comment] 2022-10-13 08:50
Finally, we've applied your workaround because it's the best option so solve the problem. The changes are included in 22.10.1+

**Closed by aimeos** 2022-10-13 08:50 UTC
