### ISSUE TITLE
Typo3 Version 7.2

### ISSUE THREAD

**Issue by boonkerz** [aimeos/aimeos-typo3#2] opened 2015-06-01 12:01 UTC
When i open the the backend module i have the following error:

```
Uncaught TYPO3 Exception
#1: PHP Warning: file_exists(): open_basedir restriction in effect. File(/usr/share/php//Aimeos/Aimeos/View/Admin/IndexHtml.php) is not within the allowed path(s): (/var/customers/webs/ag/:/var/customers/tmp/ag/:/usr/share/php/:/usr/share/php5/:/tmp/) in /var/customers/webs/ag/typo3conf/ext/aimeos/Resources/Libraries/arcavias/arcavias-core/Arcavias.php line 93 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 102.

17 TYPO3\CMS\Core\Error\ErrorHandler::handleError(2, "file_exists(): open_basedir restriction in effect.…ugustiner/:/usr/share/php/:/usr/share/php5/:/tmp/)", "/var/customers/webs/ag/typo3conf/ext/aimeo…rces/Libraries/arcavias/arcavias-core/Arcavias.php", 93, array)
16 file_exists("/usr/share/php//Aimeos/Aimeos/View/Admin/IndexHtml.php")

/var/customers/webs/ag/typo3conf/ext/aimeos/Resources/Libraries/arcavias/arcavias-core/Arcavias.php:
00091:    $file = $path . DIRECTORY_SEPARATOR . $fileName;
00092: 
00093:    if( file_exists( $file ) === true && ( include_once $file ) !== false ) {
00094:     return true;
00095:    }

15 Arcavias::autoload("Aimeos\Aimeos\View\Admin\IndexHtml")
14 spl_autoload_call("Aimeos\Aimeos\View\Admin\IndexHtml")
13 class_exists("Aimeos\Aimeos\View\Admin\IndexHtml")

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00441:   $format = $this->request->getFormat();
00442:   $viewObjectName = str_replace('@format', ucfirst($format), $possibleViewName);
00443:   if (class_exists($viewObjectName) === FALSE) {
00444:    $viewObjectName = str_replace('@format', '', $possibleViewName);
00445:   }

12 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::resolveViewObjectName()

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00311:   */
00312:  protected function resolveView() {
00313:   $viewObjectName = $this->resolveViewObjectName();
00314:   if ($viewObjectName !== FALSE) {
00315:    /** @var $view ViewInterface */

11 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::resolveView()

/var/customers/webs/ag/typo3conf/ext/aimeos/Classes/Controller/AdminController.php:
00131:  protected function resolveView()
00132:  {
00133:   return \TYPO3\CMS\Extbase\Mvc\Controller\ActionController::resolveView();
00134:  }
00135: 

10 Aimeos\Aimeos\Controller\AdminController::resolveView()

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00148:   $this->mapRequestArgumentsToControllerArguments();
00149:   $this->controllerContext = $this->buildControllerContext();
00150:   $this->view = $this->resolveView();
00151:   if ($this->view !== NULL) {
00152:    $this->initializeView($this->view);

9 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::processRequest(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php:
00068:    $controller = $this->resolveController($request);
00069:    try {
00070:     $controller->processRequest($request, $response);
00071:    } catch (\TYPO3\CMS\Extbase\Mvc\Exception\StopActionException $ignoredException) {
00072:    }

8 TYPO3\CMS\Extbase\Mvc\Dispatcher::dispatch(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Mvc/Web/BackendRequestHandler.php:
00029:   /** @var $response \TYPO3\CMS\Extbase\Mvc\ResponseInterface */
00030:   $response = $this->objectManager->get(\TYPO3\CMS\Extbase\Mvc\Web\Response::class);
00031:   $this->dispatcher->dispatch($request, $response);
00032:   return $response;
00033:  }

7 TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler::handleRequest()

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Core/Bootstrap.php:
00194:   $requestHandler = $requestHandlerResolver->resolveRequestHandler();
00195: 
00196:   $response = $requestHandler->handleRequest();
00197:   // If response is NULL after handling the request we need to stop
00198:   // This happens for instance, when a USER object was converted to a USER_INT

6 TYPO3\CMS\Extbase\Core\Bootstrap::handleRequest()

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Core/Bootstrap.php:
00183:  public function run($content, $configuration) {
00184:   $this->initialize($configuration);
00185:   return $this->handleRequest();
00186:  }
00187: 

5 TYPO3\CMS\Extbase\Core\Bootstrap::run("", array)

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/extbase/Classes/Core/ModuleRunner.php:
00065: 
00066:   $bootstrap = $this->objectManager->get(\TYPO3\CMS\Extbase\Core\BootstrapInterface::class);
00067:   $content = $bootstrap->run('', $configuration);
00068:   print $content;
00069: 

4 TYPO3\CMS\Extbase\Core\ModuleRunner::callModule("web_AimeosTxAimeosAdmin")

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/backend/Classes/BackendModuleRequestHandler.php:
00138:    foreach ($this->moduleRegistry['_dispatcher'] as $dispatcherClassName) {
00139:     $dispatcher = GeneralUtility::makeInstance(ObjectManager::class)->get($dispatcherClassName);
00140:     if ($dispatcher->callModule($moduleName) === TRUE) {
00141:      return TRUE;
00142:      break;

3 TYPO3\CMS\Backend\BackendModuleRequestHandler::dispatchModule("web_AimeosTxAimeosAdmin")

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/backend/Classes/BackendModuleRequestHandler.php:
00070:   $moduleName = (string)GeneralUtility::_GET('M');
00071:   if ($this->isDispatchedModule($moduleName)) {
00072:    $isDispatched = $this->dispatchModule($moduleName);
00073:   } else {
00074:    $isDispatched = $this->callTraditionalModule($moduleName);

2 TYPO3\CMS\Backend\BackendModuleRequestHandler::handleRequest()

/var/customers/webs/ag/typo3_src-7.2.0/typo3/sysext/core/Classes/Core/Bootstrap.php:
00189:   $this->registerRequestHandlers();
00190:   $requestHandler = $this->resolveRequestHandler();
00191:   $requestHandler->handleRequest();
00192:   return $this;
00193:  }

1 TYPO3\CMS\Core\Core\Bootstrap::run("typo3/")

/var/customers/webs/ag/typo3_src-7.2.0/typo3/mod.php:
00022: define('TYPO3_MODE', 'BE');
00023: require __DIR__ . '/sysext/core/Classes/Core/Bootstrap.php';
00024: \TYPO3\CMS\Core\Core\Bootstrap::getInstance()->run('typo3/')->shutdown();
```

**Comment by aimeos** [comment] 2015-06-01 12:25
Tried the same in a fresh TYPO3 installation and it works without problems.

According to the error message, the open_basedir setting causes this error, but I think the problem is a different one. Normally, resolving the view template (Admin/Index.html in this case) should not result in invoking the class autoloader. Did you configure anything view related in your installation or have you installed extensions like Flux, TemplaVoila or GridElements?

**Comment by boonkerz** [comment] 2015-06-01 12:42
Gridelements

**Comment by aimeos** [comment] 2015-06-01 12:50
Can you install a fresh TYPO3 7.2 in your environment and the Aimeos extension afterwards? Maybe we can isolate the problem step by step.

**Comment by boonkerz** [comment] 2015-06-01 13:10
Same Issue can i get you an login? in an private channel?

**Comment by aimeos** [comment] 2015-06-01 13:31
Sure, send us an e-mail to aimeos@aimeos.org

**Comment by boonkerz** [comment] 2015-06-01 14:38
Ok when i disable openbase dir it works :)

**Comment by aimeos** [comment] 2015-06-01 14:54
Maybe the list of allowed directories was too restrictive

**Closed** 2015-06-02 13:05 UTC
